import { ISettings, ISettingsTree } from "../../workbench.types.js";
import { getThemeIcon } from "../../browser/media/icons.js";

export const settingsTree: ISettingsTree[] = [
  {
    name: "Editor",
    icon: getThemeIcon("edit"),
    key: "editor",
    children: [
      {
        name: "Text",
        content: "",
        key: "editorText",
        icon: getThemeIcon("text"),
      },
      {
        name: "Tab Size",
        content: "",
        key: "editorTabSize",
        icon: getThemeIcon("tabs"),
      },
      {
        name: "Word Wrap",
        content: "",
        key: "editorWordWrap",
        icon: getThemeIcon("word"),
      },
      {
        name: "Auto Save",
        content: "",
        key: "editorAutoSave",
        icon: getThemeIcon("save"),
      },
      {
        name: "Cursor",
        content: "",
        key: "editorCursor",
        icon: getThemeIcon("text"),
      },
    ],
  },
  {
    name: "Appearance",
    icon: getThemeIcon("colors"),
    key: "appearance",
    children: [
      {
        name: "Theme",
        content: "",
        key: "appearanceTheme",
        icon: getThemeIcon("theme"),
      },
      {
        name: "Font Size",
        content: "",
        key: "appearanceFontSize",
        icon: getThemeIcon("text"),
      },
      {
        name: "Zoom",
        content: "",
        key: "appearanceZoom",
        icon: getThemeIcon("sync"),
      },
    ],
  },
  {
    name: "Terminal",
    icon: getThemeIcon("terminal"),
    key: "terminal",
    children: [
      {
        name: "Shell",
        content: "",
        key: "terminalShell",
        icon: getThemeIcon("terminal"),
      },
      {
        name: "Font",
        content: "",
        key: "terminalFont",
        icon: getThemeIcon("text"),
      },
    ],
  },
  {
    name: "Files",
    icon: getThemeIcon("file"),
    key: "files",
    children: [
      {
        name: "Auto Save",
        content: "",
        key: "filesAutoSave",
        icon: getThemeIcon("save"),
      },
      {
        name: "Encoding",
        content: "",
        key: "filesEncoding",
        icon: getThemeIcon("error"),
      },
    ],
  },
];

export const settingsContent: ISettings = {
  settings: [
    {
      key: "editorText",
      content: [
        {
          parentKey: "editorText",
          key: "editorText.fontFamily",
          label: "Font Family",
          description: "Controls the font family used in the editor.",
          type: "select",
          default: "Jetbrains Mono, monospace",
          options: [
            "Jetbrains Mono, monospace",
            "Fira Code, monospace",
            "Consolas, monospace",
            "Monaco, monospace",
          ],
        },
        {
          parentKey: "editorText",
          key: "editorText.fontSize",
          label: "Font Size",
          description: "Controls the font size in pixels.",
          type: "number",
          default: 14,
          min: 8,
          max: 32,
          step: 1,
        },
        {
          parentKey: "editorText",
          key: "editorText.lineHeight",
          label: "Line Height",
          description:
            "Controls the line height. Use 0 to compute automatically.",
          type: "number",
          default: 0,
          min: 0,
          max: 50,
          step: 1,
        },
        {
          parentKey: "editorText",
          key: "editorText.fontWeight",
          label: "Font Weight",
          description: "Controls the font weight.",
          type: "select",
          default: "normal",
          options: [
            "normal",
            "bold",
            "100",
            "200",
            "300",
            "400",
            "500",
            "600",
            "700",
            "800",
            "900",
          ],
        },
      ],
    },
    {
      key: "editorTabSize",
      content: [
        {
          parentKey: "editorTabSize",
          key: "editorTabSize.size",
          label: "Tab Size",
          description: "The number of spaces a tab is equal to.",
          type: "number",
          default: 2,
          min: 1,
          max: 8,
          step: 1,
        },
        {
          parentKey: "editorTabSize",
          key: "editorTabSize.insertSpaces",
          label: "Insert Spaces",
          description: "Insert spaces when pressing Tab.",
          type: "checkbox",
          default: true,
        },
        {
          parentKey: "editorTabSize",
          key: "editorTabSize.detectIndentation",
          label: "Detect Indentation",
          description: "Automatically detect indentation from file content.",
          type: "checkbox",
          default: true,
        },
      ],
    },
    {
      key: "editorWordWrap",
      content: [
        {
          parentKey: "editorWordWrap",
          key: "editorWordWrap.mode",
          label: "Word Wrap",
          description: "Controls how lines should wrap.",
          type: "select",
          default: "off",
          options: ["off", "on", "wordWrapColumn", "bounded"],
        },
        {
          parentKey: "editorWordWrap",
          key: "editorWordWrap.column",
          label: "Word Wrap Column",
          description:
            "Controls the wrapping column when wordWrap is 'wordWrapColumn'.",
          type: "number",
          default: 80,
          min: 1,
          max: 200,
          step: 1,
        },
      ],
    },
    {
      key: "editorAutoSave",
      content: [
        {
          parentKey: "editorAutoSave",
          key: "editorAutoSave.enabled",
          label: "Auto Save",
          description: "Enable auto save of dirty files.",
          type: "checkbox",
          default: true,
        },
        {
          parentKey: "editorAutoSave",
          key: "editorAutoSave.delay",
          label: "Auto Save Delay",
          description:
            "Delay in milliseconds after which an editor is saved automatically.",
          type: "range",
          default: 1000,
          min: 100,
          max: 5000,
          step: 100,
        },
      ],
    },
    {
      key: "editorCursor",
      content: [
        {
          parentKey: "editorCursor",
          key: "editorCursor.style",
          label: "Cursor Style",
          description: "Controls the cursor style.",
          type: "select",
          default: "line",
          options: [
            "line",
            "block",
            "underline",
            "line-thin",
            "block-outline",
            "underline-thin",
          ],
        },
        {
          parentKey: "editorCursor",
          key: "editorCursor.blinking",
          label: "Cursor Blinking",
          description: "Controls the cursor animation style.",
          type: "select",
          default: "blink",
          options: ["blink", "smooth", "phase", "expand", "solid"],
        },
        {
          parentKey: "editorCursor",
          key: "editorCursor.smoothCaretAnimation",
          label: "Smooth Caret Animation",
          description: "Enable smooth caret animation.",
          type: "checkbox",
          default: false,
        },
      ],
    },
    {
      key: "appearanceTheme",
      content: [
        {
          parentKey: "appearanceTheme",
          key: "appearanceTheme.colorTheme",
          label: "Color Theme",
          description: "Specifies the color theme used in the workbench.",
          type: "select",
          default: "Dark",
          options: ["Dark", "Light", "High Contrast"],
        },
        {
          parentKey: "appearanceTheme",
          key: "appearanceTheme.iconTheme",
          label: "Icon Theme",
          description: "Specifies the icon theme used in the workbench.",
          type: "select",
          default: "Default",
          options: ["Default", "Minimal", "None"],
        },
      ],
    },
    {
      key: "appearanceFontSize",
      content: [
        {
          parentKey: "appearanceFontSize",
          key: "appearanceFontSize.ui",
          label: "UI Font Size",
          description: "Controls the font size of the UI in pixels.",
          type: "range",
          default: 13,
          min: 10,
          max: 20,
          step: 1,
        },
        {
          parentKey: "appearanceFontSize",
          key: "appearanceFontSize.terminal",
          label: "Terminal Font Size",
          description: "Controls the font size of the terminal in pixels.",
          type: "number",
          default: 14,
          min: 8,
          max: 32,
          step: 1,
        },
      ],
    },
    {
      key: "appearanceZoom",
      content: [
        {
          parentKey: "appearanceZoom",
          key: "appearanceZoom.level",
          label: "Zoom Level",
          description:
            "Adjust the zoom level of the window. The default is 0 and each increment increases the zoom by 20%.",
          type: "range",
          default: 0,
          min: -5,
          max: 5,
          step: 1,
        },
      ],
    },
    {
      key: "terminalShell",
      content: [
        {
          parentKey: "terminalShell",
          key: "terminalShell.path",
          label: "Shell Path",
          description: "The path of the shell to use in the terminal.",
          type: "input",
          default: "/bin/bash",
          placeholder: "/bin/bash",
        },
        {
          parentKey: "terminalShell",
          key: "terminalShell.args",
          label: "Shell Arguments",
          description: "Arguments to pass to the shell.",
          type: "input",
          default: "",
          placeholder: "-l",
        },
      ],
    },
    {
      key: "terminalFont",
      content: [
        {
          parentKey: "terminalFont",
          key: "terminalFont.family",
          label: "Font Family",
          description: "Controls the font family of the terminal.",
          type: "select",
          default: "Jetbrains Mono, monospace",
          options: [
            "Jetbrains Mono, monospace",
            "Fira Code, monospace",
            "Consolas, monospace",
            "Monaco, monospace",
          ],
        },
        {
          parentKey: "terminalFont",
          key: "terminalFont.size",
          label: "Font Size",
          description: "Controls the font size in pixels of the terminal.",
          type: "number",
          default: 14,
          min: 8,
          max: 32,
          step: 1,
        },
      ],
    },
    {
      key: "filesAutoSave",
      content: [
        {
          parentKey: "filesAutoSave",
          key: "filesAutoSave.enabled",
          label: "Auto Save",
          description: "Controls auto save of dirty files.",
          type: "checkbox",
          default: true,
        },
        {
          parentKey: "filesAutoSave",
          key: "filesAutoSave.afterDelay",
          label: "Auto Save After Delay",
          description: "Save files after a configured delay.",
          type: "checkbox",
          default: true,
        },
      ],
    },
    {
      key: "filesEncoding",
      content: [
        {
          parentKey: "filesEncoding",
          key: "filesEncoding.default",
          label: "Default Encoding",
          description: "The default character set encoding to use.",
          type: "select",
          default: "utf8",
          options: [
            "utf8",
            "utf16le",
            "utf16be",
            "windows1252",
            "iso88591",
            "shiftjis",
          ],
        },
        {
          parentKey: "filesEncoding",
          key: "filesEncoding.autoGuess",
          label: "Auto Guess Encoding",
          description:
            "When enabled, will attempt to guess the character set encoding.",
          type: "checkbox",
          default: false,
        },
      ],
    },
  ],
};
