import { theme } from "../theme/theme.service";
import { monaco } from "./editor.helper";

const _kind = theme.get_active().base;
const _background = theme.get_color("editor.background");
const _foreground = theme.get_color("editor.foreground");
const _cursor = theme.get_color("editor.cursor.foreground");
const _lineHighlight = theme.get_color("editor.line.highlight.background");

const _borderForeground = theme.get_color("workbench.border");
const _inputBackground = theme.get_color("input.background");
const _scrollbarThumb = theme.get_color("scrollbar.thumb.foreground");
const _scrollbarThumbHover = theme.get_color(
  "scrollbar.thumb.hover.foreground",
);
const _scrollbarThumbActive = theme.get_color(
  "scrollbar.thumb.active.foreground",
);

monaco.editor.defineTheme("theme", {
  base: _kind === "light" ? "vs" : "vs-dark",
  inherit: true,
  colors: {
    "editor.background": _background,
    "editor.foreground": _foreground,
    "editorCursor.foreground": _cursor,
    "editor.lineHighlightBorder": _background,
    "editor.lineHighlightBackground": _lineHighlight,

    "editorWidget.foreground": _foreground,
    "editorWidget.border": _borderForeground,
    "editorWidget.resizeBorder": _borderForeground,

    "editorSuggestWidget.foreground": _foreground,
    "editorSuggestWidget.border": _borderForeground,

    "editorSuggestWidget.selectedForeground": _foreground,
    "editorSuggestWidget.selectedIconForeground": _foreground,

    "editorHoverWidget.foreground": _foreground,
    "editorHoverWidget.border": _borderForeground,

    "editorParameterHint.foreground": _foreground,
    "editorFindWidget.foreground": _foreground,
    "editorFindWidget.border": _borderForeground,
    "editorFindWidget.resizeBorder": _borderForeground,

    "peekViewResult.foreground": _foreground,
    "peekViewResult.lineForeground": _foreground,
    "peekViewResult.selectionForeground": _foreground,
    "peekViewTitleLabel.foreground": _foreground,

    "menu.foreground": _foreground,
    "menu.border": _borderForeground,
    "menu.selectionForeground": _foreground,
    "menu.separatorBackground": _borderForeground,

    "input.background": _inputBackground,
    "input.foreground": _foreground,
    "input.border": _borderForeground,

    "dropdown.foreground": _foreground,
    "dropdown.border": _borderForeground,

    "quickInput.foreground": _foreground,

    "notifications.foreground": _foreground,
    "notifications.border": _borderForeground,

    "breadcrumb.foreground": _foreground,

    "minimap.background": _background,

    "scrollbar.shadow": "transparent",
    "scrollbarSlider.background": _scrollbarThumb,
    "scrollbarSlider.hoverBackground": _scrollbarThumbHover,
    "scrollbarSlider.activeBackground": _scrollbarThumbActive,

    "editorOverviewRuler.background": _background,
    "editorOverviewRuler.border": _borderForeground,

    "editorGroup.background": _background,
    "editorGroupHeader.tabsBackground": theme.get_color(
      "editor.tab.background",
    ),
    "editorGroupHeader.tabsBorder": _borderForeground,
  },
  rules: [
    // Comments
    { token: "comment", foreground: "#E4E4E45E", fontStyle: "italic" },
    { token: "comment.line", foreground: "#E4E4E45E", fontStyle: "italic" },
    { token: "comment.block", foreground: "#E4E4E45E", fontStyle: "italic" },
    {
      token: "comment.block.documentation",
      foreground: "#E4E4E45E",
      fontStyle: "italic",
    },

    // Strings
    { token: "string", foreground: "#e394dc" },
    { token: "string.quoted", foreground: "#e394dc" },
    { token: "string.quoted.binary.single.python", foreground: "#a8cc7c" },
    { token: "string.regexp", foreground: "#d6d6dd" },
    { token: "string.other.link.title.markdown", foreground: "#aaa0fa" },
    { token: "string.other.link.description.markdown", foreground: "#aaa0fa" },

    // Numbers / Constants
    { token: "number", foreground: "#ebc88d" },
    { token: "constant.numeric", foreground: "#ebc88d" },
    { token: "constant.language", foreground: "#d6d6dd" },
    { token: "constant.language.false.cpp", foreground: "#82d2ce" },
    { token: "constant.language.true.cpp", foreground: "#82d2ce" },
    { token: "constant.language.symbol.ruby", foreground: "#d6d6dd" },
    { token: "constant.language.symbol.elixir", foreground: "#d6d6dd" },
    { token: "constant.other.ellipsis.python", foreground: "#CCCCCC" },
    { token: "constant.other.color", foreground: "#ebc88d" },
    { token: "constant.other.symbol", foreground: "#d6d6dd" },
    { token: "constant.character.escape", foreground: "#d6d6dd" },
    { token: "constant.character.entity", foreground: "#d6d6dd" },
    {
      token: "constant.character.format.placeholder.other.python",
      foreground: "#f8c762",
    },
    {
      token: "constant.character.character-class.regexp.xi",
      foreground: "#d6d6dd",
    },
    { token: "constant.regexp.xi", foreground: "#82D2CE" },
    { token: "constant.keyword.clojure", foreground: "#d6d6dd" },
    { token: "constant.json", foreground: "#f8c762" },
    { token: "support.constant.math", foreground: "#efb080" },
    { token: "support.constant.property.math", foreground: "#f8c762" },
    { token: "support.constant.core.rust", foreground: "#f8c762" },
    { token: "support.constant.edge", foreground: "#82D2CE" },
    { token: "support.constant.elm", foreground: "#f8c762" },
    { token: "support.constant.json", foreground: "#f8c762" },
    { token: "support.constant.ext.php", foreground: "#f8c762" },
    { token: "support.constant.std.php", foreground: "#f8c762" },
    { token: "support.constant.core.php", foreground: "#f8c762" },
    { token: "support.constant.parser-token.php", foreground: "#f8c762" },
    { token: "support.constant.laravel-blade", foreground: "#82D2CE" },

    // Keywords
    { token: "keyword", foreground: "#82D2CE" },
    { token: "keyword.control", foreground: "#82D2CE" },
    { token: "keyword.control.directive", foreground: "#a8cc7c" },
    { token: "keyword.control.directive.include.cpp", foreground: "#a8cc7c" },
    { token: "keyword.control.import.python", fontStyle: "italic" },
    { token: "keyword.control.flow.python", fontStyle: "italic" },
    { token: "keyword.control.xi", foreground: "#d6d6dd" },
    { token: "keyword.operator", foreground: "#d6d6dd" },
    { token: "keyword.operator.logical", foreground: "#d6d6dd" },
    { token: "keyword.operator.logical.python", foreground: "#82D2CE" },
    { token: "keyword.operator.bitwise", foreground: "#d6d6dd" },
    { token: "keyword.operator.arithmetic", foreground: "#d6d6dd" },
    { token: "keyword.operator.comparison", foreground: "#d6d6dd" },
    { token: "keyword.operator.decrement", foreground: "#d6d6dd" },
    { token: "keyword.operator.increment", foreground: "#d6d6dd" },
    { token: "keyword.operator.relational", foreground: "#d6d6dd" },
    { token: "keyword.operator.channel", foreground: "#d6d6dd" },
    { token: "keyword.operator.css", foreground: "#d6d6dd" },
    { token: "keyword.operator.scss", foreground: "#d6d6dd" },
    { token: "keyword.operator.less", foreground: "#d6d6dd" },
    { token: "keyword.operator.quantifier.regexp", foreground: "#f8c762" },
    { token: "keyword.operator.expression.import", foreground: "#aaa0fa" },
    { token: "keyword.operator.expression.instanceof", foreground: "#82D2CE" },
    { token: "keyword.operator.expression.keyof", foreground: "#82D2CE" },
    { token: "keyword.operator.expression.delete", foreground: "#82D2CE" },
    { token: "keyword.operator.expression.in", foreground: "#82D2CE" },
    { token: "keyword.operator.expression.of", foreground: "#82D2CE" },
    { token: "keyword.operator.expression.typeof", foreground: "#82D2CE" },
    { token: "keyword.operator.expression.void", foreground: "#82D2CE" },
    { token: "keyword.operator.new", foreground: "#82D2CE" },
    { token: "keyword.operator.ternary", foreground: "#82D2CE" },
    { token: "keyword.operator.optional", foreground: "#82D2CE" },
    { token: "keyword.operator.assignment", foreground: "#d6d6dd" },
    { token: "keyword.operator.assignment.compound", foreground: "#82D2CE" },
    { token: "keyword.operator.assignment.compound.js", foreground: "#d6d6dd" },
    { token: "keyword.operator.assignment.compound.ts", foreground: "#d6d6dd" },
    { token: "keyword.operator.assignment.go", foreground: "#efb080" },
    { token: "keyword.operator.arithmetic.go", foreground: "#82D2CE" },
    { token: "keyword.operator.address.go", foreground: "#82D2CE" },
    { token: "keyword.operator.misc.rust", foreground: "#d6d6dd" },
    { token: "keyword.operator.sigil.rust", foreground: "#82D2CE" },
    { token: "keyword.operator.delete", foreground: "#82D2CE" },
    { token: "keyword.operator.module", foreground: "#82D2CE" },
    { token: "keyword.operator.c", foreground: "#82D2CE" },
    { token: "keyword.operator.cpp", foreground: "#82D2CE" },
    { token: "keyword.operator.assignment.c", foreground: "#82D2CE" },
    { token: "keyword.operator.comparison.c", foreground: "#82D2CE" },
    { token: "keyword.operator.increment.c", foreground: "#82D2CE" },
    { token: "keyword.operator.decrement.c", foreground: "#82D2CE" },
    { token: "keyword.operator.bitwise.shift.c", foreground: "#82D2CE" },
    { token: "keyword.operator.assignment.cpp", foreground: "#82D2CE" },
    { token: "keyword.operator.comparison.cpp", foreground: "#82D2CE" },
    { token: "keyword.operator.increment.cpp", foreground: "#82D2CE" },
    { token: "keyword.operator.decrement.cpp", foreground: "#82D2CE" },
    { token: "keyword.operator.bitwise.shift.cpp", foreground: "#82D2CE" },
    { token: "keyword.operator.sizeof.c", foreground: "#82D2CE" },
    { token: "keyword.operator.sizeof.cpp", foreground: "#82D2CE" },
    { token: "keyword.operator.error-control.php", foreground: "#82D2CE" },
    { token: "keyword.operator.type.php", foreground: "#82D2CE" },
    { token: "keyword.operator.logical.php", foreground: "#d6d6dd" },
    { token: "keyword.operator.bitwise.php", foreground: "#d6d6dd" },
    { token: "keyword.operator.arithmetic.php", foreground: "#d6d6dd" },
    { token: "keyword.operator.regexp.php", foreground: "#82D2CE" },
    { token: "keyword.operator.comparison.php", foreground: "#d6d6dd" },
    { token: "keyword.operator.heredoc.php", foreground: "#82D2CE" },
    { token: "keyword.operator.nowdoc.php", foreground: "#82D2CE" },
    { token: "keyword.other.special-method", foreground: "#aaa0fa" },
    { token: "keyword.other.unit", foreground: "#ebc88d" },
    { token: "keyword.other.template.begin", foreground: "#e394dc" },
    { token: "keyword.other.template.end", foreground: "#e394dc" },
    { token: "keyword.other.substitution.begin", foreground: "#e394dc" },
    { token: "keyword.other.substitution.end", foreground: "#e394dc" },
    { token: "keyword.operator.instanceof.java", foreground: "#82D2CE" },

    // Storage
    { token: "storage", foreground: "#82d2ce" },
    { token: "storage.type", foreground: "#82d2ce" },
    { token: "storage.modifier", foreground: "#82d2ce" },
    { token: "storage.modifier.reference", foreground: "#CCCCCC" },
    { token: "storage.modifier.pointer", foreground: "#CCCCCC" },
    { token: "storage.modifier.lifetime.rust", foreground: "#d6d6dd" },
    { token: "storage.modifier.import.java", foreground: "#efb080" },
    { token: "storage.modifier.import.groovy", foreground: "#efb080" },
    { token: "storage.type.java", foreground: "#efb080" },
    { token: "storage.type.generic.java", foreground: "#efb080" },
    { token: "storage.type.annotation.java", foreground: "#efb080" },
    { token: "storage.type.object.array.java", foreground: "#efb080" },
    { token: "storage.type.haskell", foreground: "#f8c762" },
    { token: "storage.type.php", foreground: "#efb080" },
    { token: "storage.type.cs", foreground: "#efb080" },
    { token: "storage.type.python", foreground: "#82d2ce" },

    // Variables
    { token: "variable", foreground: "#d6d6dd" },
    { token: "variable.c", foreground: "#d6d6dd" },
    { token: "variable.language", foreground: "#CC7C8A" },
    { token: "variable.language.this.cpp", foreground: "#82d2ce" },
    { token: "variable.language.rust", foreground: "#d6d6dd" },
    { token: "variable.language.super", fontStyle: "italic" },
    { token: "variable.parameter", foreground: "#d6d6dd", fontStyle: "italic" },
    { token: "variable.parameter.function", foreground: "#d6d6dd" },
    { token: "variable.parameter.function.python", foreground: "#f8c762" },
    {
      token: "variable.parameter.function.language.python",
      foreground: "#f8c762",
    },
    {
      token: "variable.parameter.function.language.special.self.python",
      foreground: "#efb080",
    },
    { token: "variable.parameter.function.js", foreground: "#d6d6dd" },
    { token: "variable.parameter.function.coffee", foreground: "#d6d6dd" },
    { token: "variable.other.readwrite", foreground: "#87C3FF" },
    { token: "variable.other.constant", foreground: "#AAA0FA" },
    { token: "variable.other.property", foreground: "#AAA0FA" },
    { token: "variable.other.property.ts", foreground: "#AAA0FA" },
    { token: "variable.other.class.js", foreground: "#efb080" },
    { token: "variable.other.class.ts", foreground: "#efb080" },
    { token: "variable.other.class.php", foreground: "#d6d6dd" },
    { token: "variable.other.generic-type.haskell", foreground: "#82D2CE" },
    { token: "variable.other.generic-type.haskell", foreground: "#82D2CE" },
    { token: "variable.function", foreground: "#efb080" },
    { token: "variable.interpolation", foreground: "#d6d6dd" },
    { token: "support.variable.magic.python", foreground: "#d6d6dd" },
    { token: "support.variable.object.process", foreground: "#d6d6dd" },
    { token: "support.variable.object.node", foreground: "#d6d6dd" },
    { token: "support.variable.property", foreground: "#AAA0FA" },
    { token: "support.variable.property.process", foreground: "#f8c762" },
    { token: "support.variable.dom", foreground: "#d6d6dd" },
    { token: "support.variable.property.dom", foreground: "#d6d6dd" },
    { token: "support.variable.semantic.hlsl", foreground: "#efb080" },
    { token: "text.variable", foreground: "#d6d6dd" },
    { token: "text.bracketed", foreground: "#d6d6dd" },

    // Functions
    { token: "entity.name.function", foreground: "#efb080" },
    { token: "entity.name.function.js", foreground: "#ebc88d" },
    { token: "entity.name.function.decorator.python", foreground: "#a8cc7c" },
    { token: "entity.name.function.xi", foreground: "#efb080" },
    { token: "support.function", foreground: "#efb080" },
    { token: "support.function.std.rust", foreground: "#aaa0fa" },
    { token: "support.function.console.js", foreground: "#ebc88d" },

    // Types / Classes
    { token: "entity.name.type", foreground: "#efb080" },
    { token: "entity.name.type.class", foreground: "#efb080" },
    { token: "entity.name.type.module", foreground: "#efb080" },
    { token: "entity.name.type.namespace", foreground: "#efb080" },
    { token: "entity.name.class", foreground: "#efb080" },
    { token: "entity.name.class.xi", foreground: "#d6d6dd" },
    { token: "entity.name.namespace", foreground: "#CCCCCC" },
    { token: "entity.name.label.cs", foreground: "#efb080" },
    {
      token: "entity.name.scope-resolution.function.call",
      foreground: "#efb080",
    },
    {
      token: "entity.name.scope-resolution.function.definition",
      foreground: "#efb080",
    },
    { token: "entity.name.lifetime.rust", foreground: "#efb080" },
    { token: "entity.name.package.go", foreground: "#efb080" },
    { token: "entity.name.goto-label.php", foreground: "#aaa0fa" },
    { token: "entity.name.tag.html", foreground: "#87c3ff" },
    { token: "entity.name.tag.laravel-blade", foreground: "#82D2CE" },
    { token: "entity.name.tag.template", foreground: "#AAA0FA" },
    { token: "entity.name.tag.script", foreground: "#AAA0FA" },
    { token: "entity.name.tag.style", foreground: "#AAA0FA" },
    { token: "entity.other.attribute-name", foreground: "#aaa0fa" },
    { token: "entity.other.attribute-name.id", foreground: "#aaa0fa" },
    { token: "entity.other.attribute-name.class.css", foreground: "#f8c762" },
    {
      token: "entity.other.attribute-name.pseudo-element",
      foreground: "#d6d6dd",
    },
    {
      token: "entity.other.attribute-name.pseudo-class",
      foreground: "#d6d6dd",
    },
    { token: "entity.other.attribute-name.js", fontStyle: "italic" },
    { token: "entity.other.attribute-name.ts", fontStyle: "italic" },
    { token: "entity.other.attribute-name.jsx", fontStyle: "italic" },
    { token: "entity.other.attribute-name.tsx", fontStyle: "italic" },
    { token: "entity.other.inherited-class", foreground: "#efb080" },
    { token: "entity.other.alias.php", foreground: "#efb080" },
    { token: "entity.global.clojure", foreground: "#efb080" },
    { token: "support.class", foreground: "#87c3ff" },
    { token: "support.type.object.console", foreground: "#d6d6dd" },
    { token: "support.type.object.dom", foreground: "#d6d6dd" },
    { token: "support.type.object.module", foreground: "#efb080" },
    { token: "support.type.python", foreground: "#82d2ce" },
    { token: "support.type.primitive.ts", foreground: "#82D2CE" },
    { token: "support.type.builtin.ts", foreground: "#82D2CE" },
    { token: "support.type.primitive.tsx", foreground: "#82D2CE" },
    { token: "support.type.builtin.tsx", foreground: "#82D2CE" },
    { token: "support.type.primitive", foreground: "#efb080" },
    { token: "support.type.type.flowtype", foreground: "#aaa0fa" },
    { token: "support.type.swift", foreground: "#efb080" },
    { token: "support.type.vb.asp", foreground: "#efb080" },
    { token: "support.type.posix-reserved.c", foreground: "#d6d6dd" },
    { token: "support.type.posix-reserved.cpp", foreground: "#d6d6dd" },
    { token: "support.type.texture.hlsl", foreground: "#82D2CE" },
    { token: "support.type.sampler.hlsl", foreground: "#82D2CE" },
    { token: "support.type.object.hlsl", foreground: "#82D2CE" },
    { token: "support.type.object.rw.hlsl", foreground: "#82D2CE" },
    { token: "support.type.fx.hlsl", foreground: "#82D2CE" },
    { token: "support.type.prelude.elm", foreground: "#d6d6dd" },
    { token: "support.module.node", foreground: "#efb080" },
    { token: "support.other.namespace.use.php", foreground: "#efb080" },
    { token: "support.other.namespace.use-as.php", foreground: "#efb080" },
    { token: "support.other.namespace.php", foreground: "#efb080" },
    { token: "support.other.php", foreground: "#aaa0fa" },

    // Punctuation
    { token: "punctuation", foreground: "#d6d6dd" },
    { token: "punctuation.definition.tag", foreground: "#A4A4A4" },
    { token: "punctuation.definition.string.begin", foreground: "#e394dc" },
    { token: "punctuation.definition.string.end", foreground: "#e394dc" },
    {
      token: "punctuation.definition.comment",
      foreground: "#E4E4E45E",
      fontStyle: "italic",
    },
    { token: "punctuation.definition.bold", foreground: "#efb080" },
    { token: "punctuation.definition.bold.markdown", foreground: "#f8c762" },
    { token: "punctuation.definition.heading.markdown", foreground: "#d6d6dd" },
    { token: "punctuation.definition.italic", foreground: "#82D2CE" },
    { token: "punctuation.definition.constant", foreground: "#f8c762" },
    {
      token: "punctuation.definition.list.begin.markdown",
      foreground: "#d6d6dd",
    },
    { token: "punctuation.definition.list.markdown", foreground: "#d6d6dd" },
    {
      token: "punctuation.definition.template-expression.begin",
      foreground: "#82D2CE",
    },
    {
      token: "punctuation.definition.template-expression.end",
      foreground: "#82D2CE",
    },
    { token: "punctuation.definition.decorator.python", foreground: "#a8cc7c" },
    { token: "punctuation.section.embedded", foreground: "#82D2CE" },
    { token: "punctuation.section.embedded.begin", foreground: "#82D2CE" },
    { token: "punctuation.section.embedded.end", foreground: "#82D2CE" },
    { token: "punctuation.separator.delimiter", foreground: "#d6d6dd" },
    { token: "punctuation.separator.key-value", foreground: "#d6d6dd" },
    { token: "punctuation.separator.list.comma.css", foreground: "#d6d6dd" },
    { token: "punctuation.separator.c", foreground: "#82D2CE" },
    { token: "punctuation.separator.cpp", foreground: "#82D2CE" },
    { token: "punctuation.quasi.element", foreground: "#82D2CE" },
    { token: "meta.brace.square", foreground: "#d6d6dd" },
    {
      token: "punctuation.definition.block.sequence.item.yaml",
      foreground: "#d6d6dd",
    },

    // Meta
    { token: "meta.tag", foreground: "#fad075" },
    { token: "meta.property-name.css", foreground: "#87c3ff" },
    { token: "meta.property-value.css", foreground: "#e394dc" },
    { token: "meta.selector", foreground: "#82D2CE" },
    { token: "meta.function.c", foreground: "#d6d6dd" },
    { token: "meta.function.cpp", foreground: "#d6d6dd" },
    { token: "meta.function.decorator.python", foreground: "#a8cc7c" },
    {
      token: "meta.function.decorator.identifier.python",
      foreground: "#d6d6dd",
    },
    { token: "meta.function-call.generic.python", foreground: "#aaa0fa" },
    { token: "meta.function-call.php", foreground: "#aaa0fa" },
    { token: "meta.function-call.object.php", foreground: "#aaa0fa" },
    { token: "meta.function-call.static.php", foreground: "#aaa0fa" },
    { token: "meta.definition.variable.name.java", foreground: "#d6d6dd" },
    { token: "meta.definition.variable.name.groovy", foreground: "#d6d6dd" },
    { token: "meta.definition.property.ts", foreground: "#AAA0FA" },
    {
      token: "meta.definition.class.inherited.classes.groovy",
      foreground: "#e394dc",
    },
    { token: "meta.object-literal.key", foreground: "#d6d6dd" },
    { token: "meta.method.java", foreground: "#aaa0fa" },
    { token: "meta.method.groovy", foreground: "#aaa0fa" },
    { token: "meta.interface.php", foreground: "#efb080" },
    { token: "meta.template.expression", foreground: "#d6d6dd" },
    { token: "meta.property.object", foreground: "#d6d6dd" },
    { token: "meta.symbol.clojure", foreground: "#d6d6dd" },
    { token: "meta.arguments.coffee", foreground: "#d6d6dd" },
    { token: "meta.scope.prerequisites.makefile", foreground: "#d6d6dd" },

    // Markup (Markdown)
    { token: "markup.heading", foreground: "#d6d6dd" },
    { token: "markup.heading.setext", foreground: "#d6d6dd" },
    { token: "markup.heading.setext.1.markdown", foreground: "#d6d6dd" },
    { token: "markup.heading.setext.2.markdown", foreground: "#d6d6dd" },
    { token: "markup.bold", foreground: "#f8c762" },
    { token: "markup.italic", foreground: "#82D2CE" },
    { token: "markup.italic.markdown", fontStyle: "italic" },
    { token: "markup.inline.raw.markdown", foreground: "#e394dc" },
    { token: "markup.inline.raw.string.markdown", foreground: "#e394dc" },
    { token: "markup.underline.link.markdown", foreground: "#82D2CE" },
    { token: "markup.underline.link.image.markdown", foreground: "#82D2CE" },
    { token: "markup.quote.markdown", foreground: "#E4E4E45E" },
    { token: "markup.changed.diff", foreground: "#efb080" },
    { token: "markup.inserted.diff", foreground: "#e394dc" },
    { token: "markup.deleted.diff", foreground: "#d6d6dd" },

    // Diff
    { token: "meta.diff.header.from-file", foreground: "#aaa0fa" },
    { token: "meta.diff.header.to-file", foreground: "#aaa0fa" },
    { token: "punctuation.definition.from-file.diff", foreground: "#aaa0fa" },
    { token: "punctuation.definition.to-file.diff", foreground: "#aaa0fa" },

    // JSON
    { token: "support.type.property-name.json", foreground: "#82d2ce" },

    // Diagnostics
    { token: "token.info-token", foreground: "#aaa0fa" },
    { token: "token.warn-token", foreground: "#f8c762" },
    { token: "token.error-token", foreground: "#F14C4C" },
    { token: "token.debug-token", foreground: "#82D2CE" },

    // Invalid
    { token: "invalid", foreground: "#d6d6dd" },
    { token: "invalid.illegal", foreground: "#d6d6dd" },
    { token: "invalid.illegal.non-null-typehinted.php", foreground: "#F14C4C" },
    { token: "invalid.xi", foreground: "#d6d6dd" },

    // Misc language-specific
    { token: "source.java", foreground: "#d6d6dd" },
    { token: "source.ini", foreground: "#e394dc" },
    {
      token: "source.json meta.structure.dictionary.json string.quoted.json",
      foreground: "#d6d6dd",
    },
    { token: "source.makefile", foreground: "#efb080" },
    { token: "selector.sass", foreground: "#d6d6dd" },
    { token: "accent.xi", foreground: "#aaa0fa" },
    { token: "wikiword.xi", foreground: "#f8c762" },
    {
      token: "beginning.punctuation.definition.quote.markdown.xi",
      foreground: "#e394dc",
    },
    {
      token: "beginning.punctuation.definition.list.markdown.xi",
      foreground: "#E4E4E45E",
    },
    {
      token: "beginning.punctuation.definition.list.markdown",
      foreground: "#d6d6dd",
    },
    { token: "constant.character.xi", foreground: "#aaa0fa" },
    { token: "constant.other.color.rgb-value.xi", foreground: "#d6d6dd" },
    { token: "punctuation.definition.tag.xi", foreground: "#E4E4E45E" },
    { token: "rgb-value", foreground: "#d6d6dd" },
    { token: "inline-color-decoration.rgb-value", foreground: "#f8c762" },
    { token: "less.rgb-value", foreground: "#f8c762" },
    { token: "block.scope.begin", foreground: "#d6d6dd" },
    { token: "block.scope.end", foreground: "#d6d6dd" },
    { token: "entity.name.section.markdown", foreground: "#d6d6dd" },
    { token: "control.elements", foreground: "#f8c762" },
    { token: "emphasis.md", foreground: "#82D2CE" },
    { token: "todo.bold", foreground: "#f8c762" },
    { token: "todo.emphasis", foreground: "#82D2CE" },
    { token: "entity.name.section", foreground: "#aaa0fa" },
    {
      token: "markup.heading punctuation.definition.heading",
      foreground: "#aaa0fa",
    },
  ],
} as monaco.editor.IStandaloneThemeData);
