import { ITheme } from "../../../../../types/theme.types";

export const light: ITheme = {
  id: "light",
  name: "Meridia Light",
  base: "light",
  colors: {
    "workbench.background": "#F0F0ED",
    "workbench.foreground": "#1A1A1A",
    "workbench.border": "#DDDDD8",

    "panel.background": "#F7F7F5",
    "panel.foreground": "#1A1A1A",
    "panel.border": "#DDDDD8",

    "editor.background": "#FFFFFF",
    "editor.foreground": "#1A1A1A",
    "editor.cursor.foreground": "#38A2E8",
    "editor.selection.background": "#BAE6FD",
    "editor.line.highlight.background": "#F5F5F3",

    "editor.tab.background": "#F0F0ED",
    "editor.tab.active.background": "#FFFFFF",
    "editor.tab.active.border": "#FFFFFF",
    "editor.tab.hover.background": "#E8E8E5",
    "editor.tab.foreground": "#7A7A72",
    "editor.tab.active.foreground": "#1A1A1A",
    "editor.tab.hover.foreground": "#1A1A1A",
    "editor.tab.border": "#DDDDD8",
    "editor.tab.icon.foreground": "#1A1A1A",
    "editor.tab.close.foreground": "#9A9A92",
    "editor.tab.close.active.background": "#D0D0CB",
    "editor.tab.close.hover.background": "#D0D0CB",

    "view.tab.background": "#F0F0ED",
    "view.tab.active.background": "#FFFFFF",
    "view.tab.hover.background": "#E8E8E5",
    "view.tab.foreground": "#7A7A72",
    "view.tab.active.foreground": "#1A1A1A",
    "view.tab.hover.foreground": "#1A1A1A",
    "view.tab.close.foreground": "#9A9A92",
    "view.tab.close.hover.background": "#D0D0CB",

    "explorer.background": "#F7F7F5",
    "explorer.foreground": "#3A3A36",
    "explorer.icon.foreground": "#6A6A62",
    "explorer.item.hover.background": "#E8E8E4",
    "explorer.item.hover.foreground": "#1A1A1A",
    "explorer.item.active.background": "#E0F2FE",
    "explorer.item.active.foreground": "#0369A1",

    "git.background": "#F7F7F5",
    "git.foreground": "#3A3A36",
    "git.modified.foreground": "#B45309",
    "git.untracked.foreground": "#047857",
    "git.ignored.foreground": "#A8A8A0",

    "problems.background": "#F7F7F5",
    "problems.foreground": "#1A1A1A",
    "problems.error.foreground": "#C0142A",
    "problems.warning.foreground": "#B45309",
    "problems.info.foreground": "#0284C7",

    "chat.background": "#F7F7F5",
    "chat.foreground": "#1A1A1A",
    "chat.user.background": "#EEEEED",
    "chat.assistant.background": "#FFFFFF",
    "chat.input.background": "#FFFFFF",
    "chat.input.foreground": "#1A1A1A",

    "terminal.background": "#F7F7F5",
    "terminal.foreground": "#1A1A1A",
    "terminal.cursor.foreground": "#1A1A1A",
    "terminal.selection.background": "#BAE6FD",

    "terminal.black": "#3A3A36",
    "terminal.red": "#C0142A",
    "terminal.green": "#166534",
    "terminal.yellow": "#B45309",
    "terminal.blue": "#38A2E8",
    "terminal.magenta": "#6D28D9",
    "terminal.cyan": "#0284C7",
    "terminal.white": "#F7F7F5",

    "terminal.bright.black": "#6A6A62",
    "terminal.bright.red": "#DC2626",
    "terminal.bright.green": "#16A34A",
    "terminal.bright.yellow": "#D97706",
    "terminal.bright.blue": "#7DD3FC",
    "terminal.bright.magenta": "#7C3AED",
    "terminal.bright.cyan": "#38BDF8",
    "terminal.bright.white": "#FFFFFF",

    "loader.foreground": "#38A2E8",

    "command.background": "#F7F7F5",
    "command.item.foreground": "#1A1A1A",
    "command.item.hover.background": "#E8E8E4",
    "command.item.hover.foreground": "#1A1A1A",
    "command.item.active.background": "#E0F2FE",
    "command.item.active.foreground": "#0369A1",

    "input.background": "#FFFFFF",
    "input.foreground": "#1A1A1A",
    "input.border": "#CECECA",
    "input.placeholder.foreground": "#AAAAA0",
    "input.focus.border": "#38A2E8",

    "select.background": "#FFFFFF",
    "select.foreground": "#1A1A1A",
    "select.border": "#CECECA",
    "select.hover.background": "#F0F0ED",
    "select.menu.background": "#FFFFFF",
    "select.option.foreground": "#1A1A1A",
    "select.option.hover.background": "#F0F0ED",
    "select.option.active.background": "#E0F2FE",

    "tooltip.background": "#2A2A28",
    "tooltip.foreground": "#F0F0ED",
    "tooltip.border": "#3A3A36",

    "button.primary.background": "#38A2E8",
    "button.primary.foreground": "#FFFFFF",
    "button.primary.hover.background": "#0284C7",
    "button.primary.active.background": "#0369A1",

    "button.secondary.background": "#E8E8E5",
    "button.secondary.foreground": "#1A1A1A",
    "button.secondary.hover.background": "#D8D8D4",
    "button.secondary.active.background": "#D0D0CB",

    "button.danger.background": "#C0142A",
    "button.danger.foreground": "#FFFFFF",
    "button.danger.hover.background": "#991B1B",

    "statusbar.background": "#E8E8E5",
    "statusbar.foreground": "#5A5A54",
    "statusbar.item.hover.background": "#D8D8D4",

    "titlebar.background": "#E8E8E5",
    "titlebar.foreground": "#5A5A54",
    "titlebar.icon.foreground": "#5A5A54",
    "titlebar.icon.hover.background": "#D0D0CB",

    "titlebar.popover.background": "#FFFFFF",

    "titlebar.menu.item.hover.background": "#D8D8D4",
    "titlebar.menu.item.hover.foreground": "#1A1A1A",
    "titlebar.menu.item.active.background": "#E0F2FE",
    "titlebar.menu.item.active.foreground": "#0369A1",

    "split.handle.foreground": "#DDDDD8",
    "split.handle.hover.foreground": "#CECECA",
    "split.handle.active.foreground": "#38A2E8",

    "scrollbar.thumb.foreground": "#CECECA",
    "scrollbar.thumb.hover.foreground": "#AAAAA0",
    "scrollbar.thumb.active.foreground": "#8A8A82",

    "selection.background": "#BAE6FD",
    "selection.foreground": "#1A1A1A",
    "focus.border": "#38A2E8",

    "context.menu.background": "#FFFFFF",
    "context.menu.foreground": "#1A1A1A",
    "context.menu.border": "#DDDDD8",
    "context.menu.item.foreground": "#1A1A1A",
    "context.menu.item.hover.background": "#F0F0ED",
    "context.menu.item.hover.foreground": "#1A1A1A",

    "popover.background": "#FFFFFF",
    "popover.border": "#DDDDD8",
    "popover.content.background": "#FFFFFF",
    "popover.content.foreground": "#1A1A1A",
    "popover.shadow": "0 8px 32px rgba(0, 0, 0, 0.10)",

    "insights.background": "#F0F0ED",
    "insights.foreground": "#5A5A54",

    "link.foreground": "#38A2E8",
    "link.hover.foreground": "#0284C7",
  },
};
