import { h } from "../../core/dom/h";
import { cn } from "../../core/utils/cn";
import { VirtualTree } from "../../ui";

export function Explorer() {
  const tree = VirtualTree({
    rowHeight: 28,
    height: "full",
    // class: "h-full",
    roots: [
      {
        id: "src",
        label: "src",
        icon: "folder",
        defaultOpen: true,
        children: [
          { id: "main", label: "main.ts", icon: "file-code" },
          {
            id: "ui",
            label: "ui",
            icon: "folder",
            defaultOpen: true,
            children: [
              { id: "button", label: "button.ts", icon: "file-code" },
              { id: "select", label: "select.ts", icon: "file-code" },
            ],
          },
        ],
      },
      { id: "pkg", label: "package.json", icon: "json" },
    ],
    onSelect: (id) => console.log("select", id),
  });

  const el = h(
    "div",
    {
      class: cn("h-full w-full", "bg-explorer-background"),
    },
    tree.el,
  );

  setTimeout(() => {
    tree.setRoots([
      {
        id: "src",
        label: "src",
        icon: "folder",
        defaultOpen: true,
        children: [
          { id: "main", label: "main.ts", icon: "file-code" },
          {
            id: "ui",
            label: "ui",
            icon: "folder",
            defaultOpen: true,
            children: [
              { id: "button", label: "button.ts", icon: "file-code" },
              { id: "select", label: "select.ts", icon: "file-code" },
            ],
          },
        ],
      },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
      { id: "pkg", label: "package.json", icon: "json" },
    ]);
  }, 1000);

  return el;
}
