import { h } from "../../core/dom/h";
import { cn } from "../../core/utils/cn";
import { open_editor_tab } from "../../services/editor/editor.helper";
import { get_file_icon } from "../../services/explorer/explorer.helper";
import { VirtualTree } from "../../ui";
import { stressAddBurst } from "./stress.helpers";

export function Explorer() {
  const tree = VirtualTree({
    rowHeight: 26,
    height: "full",
    get_icon: get_file_icon,
    icon_folder_name: "file-icons",
    folderStructure: {
      root: {
        name: "project-root",
      },
      path: "/",
      structure: [
        {
          id: ".github",
          type: "folder",
          name: ".github",
          path: "/.github",
          child_nodes: [
            {
              id: ".github/workflows",
              type: "folder",
              name: "workflows",
              path: "/.github/workflows",
              child_nodes: [
                {
                  id: ".github/workflows/ci.yml",
                  type: "file",
                  name: "ci.yml",
                  path: "/.github/workflows/ci.yml",
                  child_nodes: [],
                },
                {
                  id: ".github/workflows/deploy.yml",
                  type: "file",
                  name: "deploy.yml",
                  path: "/.github/workflows/deploy.yml",
                  child_nodes: [],
                },
                {
                  id: ".github/workflows/test.yml",
                  type: "file",
                  name: "test.yml",
                  path: "/.github/workflows/test.yml",
                  child_nodes: [],
                },
              ],
            },
            {
              id: ".github/ISSUE_TEMPLATE.md",
              type: "file",
              name: "ISSUE_TEMPLATE.md",
              path: "/.github/ISSUE_TEMPLATE.md",
              child_nodes: [],
            },
            {
              id: ".github/PULL_REQUEST_TEMPLATE.md",
              type: "file",
              name: "PULL_REQUEST_TEMPLATE.md",
              path: "/.github/PULL_REQUEST_TEMPLATE.md",
              child_nodes: [],
            },
          ],
        },
        {
          id: "docs",
          type: "folder",
          name: "docs",
          path: "/docs",
          child_nodes: [
            {
              id: "docs/api",
              type: "folder",
              name: "api",
              path: "/docs/api",
              child_nodes: [
                {
                  id: "docs/api/authentication.md",
                  type: "file",
                  name: "authentication.md",
                  path: "/docs/api/authentication.md",
                  child_nodes: [],
                },
                {
                  id: "docs/api/endpoints.md",
                  type: "file",
                  name: "endpoints.md",
                  path: "/docs/api/endpoints.md",
                  child_nodes: [],
                },
                {
                  id: "docs/api/rate-limiting.md",
                  type: "file",
                  name: "rate-limiting.md",
                  path: "/docs/api/rate-limiting.md",
                  child_nodes: [],
                },
              ],
            },
            {
              id: "docs/guides",
              type: "folder",
              name: "guides",
              path: "/docs/guides",
              child_nodes: [
                {
                  id: "docs/guides/getting-started.md",
                  type: "file",
                  name: "getting-started.md",
                  path: "/docs/guides/getting-started.md",
                  child_nodes: [],
                },
                {
                  id: "docs/guides/advanced-usage.md",
                  type: "file",
                  name: "advanced-usage.md",
                  path: "/docs/guides/advanced-usage.md",
                  child_nodes: [],
                },
                {
                  id: "docs/guides/troubleshooting.md",
                  type: "file",
                  name: "troubleshooting.md",
                  path: "/docs/guides/troubleshooting.md",
                  child_nodes: [],
                },
              ],
            },
            {
              id: "docs/README.md",
              type: "file",
              name: "README.md",
              path: "/docs/README.md",
              child_nodes: [],
            },
          ],
        },
        {
          id: "public",
          type: "folder",
          name: "public",
          path: "/public",
          child_nodes: [
            {
              id: "public/assets",
              type: "folder",
              name: "assets",
              path: "/public/assets",
              child_nodes: [
                {
                  id: "public/assets/fonts",
                  type: "folder",
                  name: "fonts",
                  path: "/public/assets/fonts",
                  child_nodes: [
                    {
                      id: "public/assets/fonts/roboto.woff2",
                      type: "file",
                      name: "roboto.woff2",
                      path: "/public/assets/fonts/roboto.woff2",
                      child_nodes: [],
                    },
                    {
                      id: "public/assets/fonts/roboto-bold.woff2",
                      type: "file",
                      name: "roboto-bold.woff2",
                      path: "/public/assets/fonts/roboto-bold.woff2",
                      child_nodes: [],
                    },
                    {
                      id: "public/assets/fonts/inter.woff2",
                      type: "file",
                      name: "inter.woff2",
                      path: "/public/assets/fonts/inter.woff2",
                      child_nodes: [],
                    },
                  ],
                },
                {
                  id: "public/assets/images",
                  type: "folder",
                  name: "images",
                  path: "/public/assets/images",
                  child_nodes: [
                    {
                      id: "public/assets/images/logo.svg",
                      type: "file",
                      name: "logo.svg",
                      path: "/public/assets/images/logo.svg",
                      child_nodes: [],
                    },
                    {
                      id: "public/assets/images/hero.png",
                      type: "file",
                      name: "hero.png",
                      path: "/public/assets/images/hero.png",
                      child_nodes: [],
                    },
                    {
                      id: "public/assets/images/favicon.ico",
                      type: "file",
                      name: "favicon.ico",
                      path: "/public/assets/images/favicon.ico",
                      child_nodes: [],
                    },
                  ],
                },
              ],
            },
            {
              id: "public/index.html",
              type: "file",
              name: "index.html",
              path: "/public/index.html",
              child_nodes: [],
            },
            {
              id: "public/robots.txt",
              type: "file",
              name: "robots.txt",
              path: "/public/robots.txt",
              child_nodes: [],
            },
          ],
        },
        {
          id: "src",
          type: "folder",
          name: "src",
          path: "/src",
          child_nodes: [
            {
              id: "src/components",
              type: "folder",
              name: "components",
              path: "/src/components",
              child_nodes: [
                {
                  id: "src/components/common",
                  type: "folder",
                  name: "common",
                  path: "/src/components/common",
                  child_nodes: [
                    {
                      id: "src/components/common/Button.tsx",
                      type: "file",
                      name: "Button.tsx",
                      path: "/src/components/common/Button.tsx",
                      child_nodes: [],
                    },
                    {
                      id: "src/components/common/Input.tsx",
                      type: "file",
                      name: "Input.tsx",
                      path: "/src/components/common/Input.tsx",
                      child_nodes: [],
                    },
                    {
                      id: "src/components/common/Modal.tsx",
                      type: "file",
                      name: "Modal.tsx",
                      path: "/src/components/common/Modal.tsx",
                      child_nodes: [],
                    },
                    {
                      id: "src/components/common/Select.tsx",
                      type: "file",
                      name: "Select.tsx",
                      path: "/src/components/common/Select.tsx",
                      child_nodes: [],
                    },
                    {
                      id: "src/components/common/Tooltip.tsx",
                      type: "file",
                      name: "Tooltip.tsx",
                      path: "/src/components/common/Tooltip.tsx",
                      child_nodes: [],
                    },
                  ],
                },
                {
                  id: "src/components/layout",
                  type: "folder",
                  name: "layout",
                  path: "/src/components/layout",
                  child_nodes: [
                    {
                      id: "src/components/layout/Header.tsx",
                      type: "file",
                      name: "Header.tsx",
                      path: "/src/components/layout/Header.tsx",
                      child_nodes: [],
                    },
                    {
                      id: "src/components/layout/Footer.tsx",
                      type: "file",
                      name: "Footer.tsx",
                      path: "/src/components/layout/Footer.tsx",
                      child_nodes: [],
                    },
                    {
                      id: "src/components/layout/Sidebar.tsx",
                      type: "file",
                      name: "Sidebar.tsx",
                      path: "/src/components/layout/Sidebar.tsx",
                      child_nodes: [],
                    },
                    {
                      id: "src/components/layout/Navigation.tsx",
                      type: "file",
                      name: "Navigation.tsx",
                      path: "/src/components/layout/Navigation.tsx",
                      child_nodes: [],
                    },
                  ],
                },
                {
                  id: "src/components/dashboard",
                  type: "folder",
                  name: "dashboard",
                  path: "/src/components/dashboard",
                  child_nodes: [
                    {
                      id: "src/components/dashboard/Chart.tsx",
                      type: "file",
                      name: "Chart.tsx",
                      path: "/src/components/dashboard/Chart.tsx",
                      child_nodes: [],
                    },
                    {
                      id: "src/components/dashboard/StatsCard.tsx",
                      type: "file",
                      name: "StatsCard.tsx",
                      path: "/src/components/dashboard/StatsCard.tsx",
                      child_nodes: [],
                    },
                    {
                      id: "src/components/dashboard/RecentActivity.tsx",
                      type: "file",
                      name: "RecentActivity.tsx",
                      path: "/src/components/dashboard/RecentActivity.tsx",
                      child_nodes: [],
                    },
                  ],
                },
              ],
            },
            {
              id: "src/core",
              type: "folder",
              name: "core",
              path: "/src/core",
              child_nodes: [
                {
                  id: "src/core/api",
                  type: "folder",
                  name: "api",
                  path: "/src/core/api",
                  child_nodes: [
                    {
                      id: "src/core/api/client.ts",
                      type: "file",
                      name: "client.ts",
                      path: "/src/core/api/client.ts",
                      child_nodes: [],
                    },
                    {
                      id: "src/core/api/endpoints.ts",
                      type: "file",
                      name: "endpoints.ts",
                      path: "/src/core/api/endpoints.ts",
                      child_nodes: [],
                    },
                    {
                      id: "src/core/api/interceptors.ts",
                      type: "file",
                      name: "interceptors.ts",
                      path: "/src/core/api/interceptors.ts",
                      child_nodes: [],
                    },
                  ],
                },
                {
                  id: "src/core/hooks",
                  type: "folder",
                  name: "hooks",
                  path: "/src/core/hooks",
                  child_nodes: [
                    {
                      id: "src/core/hooks/useAuth.ts",
                      type: "file",
                      name: "useAuth.ts",
                      path: "/src/core/hooks/useAuth.ts",
                      child_nodes: [],
                    },
                    {
                      id: "src/core/hooks/useDebounce.ts",
                      type: "file",
                      name: "useDebounce.ts",
                      path: "/src/core/hooks/useDebounce.ts",
                      child_nodes: [],
                    },
                    {
                      id: "src/core/hooks/useLocalStorage.ts",
                      type: "file",
                      name: "useLocalStorage.ts",
                      path: "/src/core/hooks/useLocalStorage.ts",
                      child_nodes: [],
                    },
                    {
                      id: "src/core/hooks/useTheme.ts",
                      type: "file",
                      name: "useTheme.ts",
                      path: "/src/core/hooks/useTheme.ts",
                      child_nodes: [],
                    },
                  ],
                },
                {
                  id: "src/core/utils",
                  type: "folder",
                  name: "utils",
                  path: "/src/core/utils",
                  child_nodes: [
                    {
                      id: "src/core/utils/cn.ts",
                      type: "file",
                      name: "cn.ts",
                      path: "/src/core/utils/cn.ts",
                      child_nodes: [],
                    },
                    {
                      id: "src/core/utils/format.ts",
                      type: "file",
                      name: "format.ts",
                      path: "/src/core/utils/format.ts",
                      child_nodes: [],
                    },
                    {
                      id: "src/core/utils/validation.ts",
                      type: "file",
                      name: "validation.ts",
                      path: "/src/core/utils/validation.ts",
                      child_nodes: [],
                    },
                  ],
                },
              ],
            },
            {
              id: "src/features",
              type: "folder",
              name: "features",
              path: "/src/features",
              child_nodes: [
                {
                  id: "src/features/auth",
                  type: "folder",
                  name: "auth",
                  path: "/src/features/auth",
                  child_nodes: [
                    {
                      id: "src/features/auth/components",
                      type: "folder",
                      name: "components",
                      path: "/src/features/auth/components",
                      child_nodes: [
                        {
                          id: "src/features/auth/components/LoginForm.tsx",
                          type: "file",
                          name: "LoginForm.tsx",
                          path: "/src/features/auth/components/LoginForm.tsx",
                          child_nodes: [],
                        },
                        {
                          id: "src/features/auth/components/RegisterForm.tsx",
                          type: "file",
                          name: "RegisterForm.tsx",
                          path: "/src/features/auth/components/RegisterForm.tsx",
                          child_nodes: [],
                        },
                        {
                          id: "src/features/auth/components/ForgotPassword.tsx",
                          type: "file",
                          name: "ForgotPassword.tsx",
                          path: "/src/features/auth/components/ForgotPassword.tsx",
                          child_nodes: [],
                        },
                      ],
                    },
                    {
                      id: "src/features/auth/store",
                      type: "folder",
                      name: "store",
                      path: "/src/features/auth/store",
                      child_nodes: [
                        {
                          id: "src/features/auth/store/authSlice.ts",
                          type: "file",
                          name: "authSlice.ts",
                          path: "/src/features/auth/store/authSlice.ts",
                          child_nodes: [],
                        },
                        {
                          id: "src/features/auth/store/authThunks.ts",
                          type: "file",
                          name: "authThunks.ts",
                          path: "/src/features/auth/store/authThunks.ts",
                          child_nodes: [],
                        },
                      ],
                    },
                    {
                      id: "src/features/auth/types.ts",
                      type: "file",
                      name: "types.ts",
                      path: "/src/features/auth/types.ts",
                      child_nodes: [],
                    },
                  ],
                },
                {
                  id: "src/features/profile",
                  type: "folder",
                  name: "profile",
                  path: "/src/features/profile",
                  child_nodes: [
                    {
                      id: "src/features/profile/components",
                      type: "folder",
                      name: "components",
                      path: "/src/features/profile/components",
                      child_nodes: [
                        {
                          id: "src/features/profile/components/ProfileCard.tsx",
                          type: "file",
                          name: "ProfileCard.tsx",
                          path: "/src/features/profile/components/ProfileCard.tsx",
                          child_nodes: [],
                        },
                        {
                          id: "src/features/profile/components/EditProfile.tsx",
                          type: "file",
                          name: "EditProfile.tsx",
                          path: "/src/features/profile/components/EditProfile.tsx",
                          child_nodes: [],
                        },
                        {
                          id: "src/features/profile/components/AvatarUpload.tsx",
                          type: "file",
                          name: "AvatarUpload.tsx",
                          path: "/src/features/profile/components/AvatarUpload.tsx",
                          child_nodes: [],
                        },
                      ],
                    },
                    {
                      id: "src/features/profile/store",
                      type: "folder",
                      name: "store",
                      path: "/src/features/profile/store",
                      child_nodes: [
                        {
                          id: "src/features/profile/store/profileSlice.ts",
                          type: "file",
                          name: "profileSlice.ts",
                          path: "/src/features/profile/store/profileSlice.ts",
                          child_nodes: [],
                        },
                      ],
                    },
                    {
                      id: "src/features/profile/types.ts",
                      type: "file",
                      name: "types.ts",
                      path: "/src/features/profile/types.ts",
                      child_nodes: [],
                    },
                  ],
                },
                {
                  id: "src/features/settings",
                  type: "folder",
                  name: "settings",
                  path: "/src/features/settings",
                  child_nodes: [
                    {
                      id: "src/features/settings/components",
                      type: "folder",
                      name: "components",
                      path: "/src/features/settings/components",
                      child_nodes: [
                        {
                          id: "src/features/settings/components/GeneralSettings.tsx",
                          type: "file",
                          name: "GeneralSettings.tsx",
                          path: "/src/features/settings/components/GeneralSettings.tsx",
                          child_nodes: [],
                        },
                        {
                          id: "src/features/settings/components/SecuritySettings.tsx",
                          type: "file",
                          name: "SecuritySettings.tsx",
                          path: "/src/features/settings/components/SecuritySettings.tsx",
                          child_nodes: [],
                        },
                        {
                          id: "src/features/settings/components/NotificationSettings.tsx",
                          type: "file",
                          name: "NotificationSettings.tsx",
                          path: "/src/features/settings/components/NotificationSettings.tsx",
                          child_nodes: [],
                        },
                      ],
                    },
                    {
                      id: "src/features/settings/types.ts",
                      type: "file",
                      name: "types.ts",
                      path: "/src/features/settings/types.ts",
                      child_nodes: [],
                    },
                  ],
                },
              ],
            },
            {
              id: "src/pages",
              type: "folder",
              name: "pages",
              path: "/src/pages",
              child_nodes: [
                {
                  id: "src/pages/Home.tsx",
                  type: "file",
                  name: "Home.tsx",
                  path: "/src/pages/Home.tsx",
                  child_nodes: [],
                },
                {
                  id: "src/pages/Dashboard.tsx",
                  type: "file",
                  name: "Dashboard.tsx",
                  path: "/src/pages/Dashboard.tsx",
                  child_nodes: [],
                },
                {
                  id: "src/pages/Profile.tsx",
                  type: "file",
                  name: "Profile.tsx",
                  path: "/src/pages/Profile.tsx",
                  child_nodes: [],
                },
                {
                  id: "src/pages/Settings.tsx",
                  type: "file",
                  name: "Settings.tsx",
                  path: "/src/pages/Settings.tsx",
                  child_nodes: [],
                },
                {
                  id: "src/pages/NotFound.tsx",
                  type: "file",
                  name: "NotFound.tsx",
                  path: "/src/pages/NotFound.tsx",
                  child_nodes: [],
                },
              ],
            },
            {
              id: "src/services",
              type: "folder",
              name: "services",
              path: "/src/services",
              child_nodes: [
                {
                  id: "src/services/analytics.ts",
                  type: "file",
                  name: "analytics.ts",
                  path: "/src/services/analytics.ts",
                  child_nodes: [],
                },
                {
                  id: "src/services/logger.ts",
                  type: "file",
                  name: "logger.ts",
                  path: "/src/services/logger.ts",
                  child_nodes: [],
                },
                {
                  id: "src/services/storage.ts",
                  type: "file",
                  name: "storage.ts",
                  path: "/src/services/storage.ts",
                  child_nodes: [],
                },
              ],
            },
            {
              id: "src/store",
              type: "folder",
              name: "store",
              path: "/src/store",
              child_nodes: [
                {
                  id: "src/store/index.ts",
                  type: "file",
                  name: "index.ts",
                  path: "/src/store/index.ts",
                  child_nodes: [],
                },
                {
                  id: "src/store/rootReducer.ts",
                  type: "file",
                  name: "rootReducer.ts",
                  path: "/src/store/rootReducer.ts",
                  child_nodes: [],
                },
                {
                  id: "src/store/middleware.ts",
                  type: "file",
                  name: "middleware.ts",
                  path: "/src/store/middleware.ts",
                  child_nodes: [],
                },
              ],
            },
            {
              id: "src/styles",
              type: "folder",
              name: "styles",
              path: "/src/styles",
              child_nodes: [
                {
                  id: "src/styles/global.css",
                  type: "file",
                  name: "global.css",
                  path: "/src/styles/global.css",
                  child_nodes: [],
                },
                {
                  id: "src/styles/variables.css",
                  type: "file",
                  name: "variables.css",
                  path: "/src/styles/variables.css",
                  child_nodes: [],
                },
                {
                  id: "src/styles/reset.css",
                  type: "file",
                  name: "reset.css",
                  path: "/src/styles/reset.css",
                  child_nodes: [],
                },
              ],
            },
            {
              id: "src/types",
              type: "folder",
              name: "types",
              path: "/src/types",
              child_nodes: [
                {
                  id: "src/types/api.types.ts",
                  type: "file",
                  name: "api.types.ts",
                  path: "/src/types/api.types.ts",
                  child_nodes: [],
                },
                {
                  id: "src/types/global.d.ts",
                  type: "file",
                  name: "global.d.ts",
                  path: "/src/types/global.d.ts",
                  child_nodes: [],
                },
                {
                  id: "src/types/models.types.ts",
                  type: "file",
                  name: "models.types.ts",
                  path: "/src/types/models.types.ts",
                  child_nodes: [],
                },
              ],
            },
            {
              id: "src/App.tsx",
              type: "file",
              name: "App.tsx",
              path: "/src/App.tsx",
              child_nodes: [],
            },
            {
              id: "src/main.ts",
              type: "file",
              name: "main.ts",
              path: "/src/main.ts",
              child_nodes: [],
            },
            {
              id: "src/vite-env.d.ts",
              type: "file",
              name: "vite-env.d.ts",
              path: "/src/vite-env.d.ts",
              child_nodes: [],
            },
          ],
        },
        {
          id: "tests",
          type: "folder",
          name: "tests",
          path: "/tests",
          child_nodes: [
            {
              id: "tests/unit",
              type: "folder",
              name: "unit",
              path: "/tests/unit",
              child_nodes: [
                {
                  id: "tests/unit/components.test.ts",
                  type: "file",
                  name: "components.test.ts",
                  path: "/tests/unit/components.test.ts",
                  child_nodes: [],
                },
                {
                  id: "tests/unit/utils.test.ts",
                  type: "file",
                  name: "utils.test.ts",
                  path: "/tests/unit/utils.test.ts",
                  child_nodes: [],
                },
                {
                  id: "tests/unit/hooks.test.ts",
                  type: "file",
                  name: "hooks.test.ts",
                  path: "/tests/unit/hooks.test.ts",
                  child_nodes: [],
                },
              ],
            },
            {
              id: "tests/integration",
              type: "folder",
              name: "integration",
              path: "/tests/integration",
              child_nodes: [
                {
                  id: "tests/integration/auth.test.ts",
                  type: "file",
                  name: "auth.test.ts",
                  path: "/tests/integration/auth.test.ts",
                  child_nodes: [],
                },
                {
                  id: "tests/integration/api.test.ts",
                  type: "file",
                  name: "api.test.ts",
                  path: "/tests/integration/api.test.ts",
                  child_nodes: [],
                },
              ],
            },
            {
              id: "tests/e2e",
              type: "folder",
              name: "e2e",
              path: "/tests/e2e",
              child_nodes: [
                {
                  id: "tests/e2e/login.spec.ts",
                  type: "file",
                  name: "login.spec.ts",
                  path: "/tests/e2e/login.spec.ts",
                  child_nodes: [],
                },
                {
                  id: "tests/e2e/dashboard.spec.ts",
                  type: "file",
                  name: "dashboard.spec.ts",
                  path: "/tests/e2e/dashboard.spec.ts",
                  child_nodes: [],
                },
              ],
            },
            {
              id: "tests/setup.ts",
              type: "file",
              name: "setup.ts",
              path: "/tests/setup.ts",
              child_nodes: [],
            },
          ],
        },
        {
          id: ".env.example",
          type: "file",
          name: ".env.example",
          path: "/.env.example",
          child_nodes: [],
        },
        {
          id: ".eslintrc.json",
          type: "file",
          name: ".eslintrc.json",
          path: "/.eslintrc.json",
          child_nodes: [],
        },
        {
          id: ".gitignore",
          type: "file",
          name: ".gitignore",
          path: "/.gitignore",
          child_nodes: [],
        },
        {
          id: ".prettierrc",
          type: "file",
          name: ".prettierrc",
          path: "/.prettierrc",
          child_nodes: [],
        },
        {
          id: "package.json",
          type: "file",
          name: "package.json",
          path: "/package.json",
          child_nodes: [],
        },
        {
          id: "package-lock.json",
          type: "file",
          name: "package-lock.json",
          path: "/package-lock.json",
          child_nodes: [],
        },
        {
          id: "README.md",
          type: "file",
          name: "README.md",
          path: "/README.md",
          child_nodes: [],
        },
        {
          id: "tsconfig.json",
          type: "file",
          name: "tsconfig.json",
          path: "/tsconfig.json",
          child_nodes: [],
        },
        {
          id: "vite.config.ts",
          type: "file",
          name: "vite.config.ts",
          path: "/vite.config.ts",
          child_nodes: [],
        },
      ],
    },
    onSelect: (id) => open_editor_tab(id),
  });

  const el = h(
    "div",
    {
      class: cn("h-full w-full", "bg-explorer-background"),
    },
    tree.el,
  );

  return el;
}
