import { ITheme } from "../../workbench/workbench.types.js";

export const Light: ITheme = {
  name: "Light",
  kind: "light",
  colors: {
    "workbench.background": "#f0f0f0",
    "workbench.foreground": "#1e1e1e",
    "workbench.secondary.foreground": "#424242",
    "workbench.border.foreground": "#d4d4d4",
    "workbench.icon.foreground": "#424242",
    "workbench.item.hover.background": "#e8e8e8",
    "workbench.primary.button.background": "#007acc",
    "workbench.primary.button.foreground": "#ffffff",
    "workbench.secondary.button.background": "#e1e1e1",
    "workbench.secondary.button.foreground": "#424242",
    "workbench.button.border": "#d4d4d4",
    "workbench.button.separator": "#d4d4d4",
    "workbench.secondary.button.border": "#d4d4d4",

    "workbench.input.background": "#ffffff",
    "workbench.input.foreground": "#1e1e1e",
    "workbench.input.active.outline": "#007acc",
    "workbench.input.outline": "#d4d4d4",
    "workbench.input.icon.foreground": "#424242",

    "workbench.tabs.background": "#ffffff",
    "workbench.tabs.foreground": "#424242",
    "workbench.tabs.icon.foreground": "#ffffffclear",
    "workbench.tabs.hover.background": "#e8e8e8",
    "workbench.tabs.hover.foreground": "#1e1e1e",
    "workbench.tabs.active.background": "#212121",
    "workbench.tabs.active.foreground": "#1e1e1e",
    "workbench.tabs.active.border.foreground": "#007acc",

    "workbench.scrollbar.background": "transparent",
    "workbench.scrollbar.thumb.foreground": "#c8c8c8",
    "workbench.scrollbar.thumb.hover.foreground": "#a6a6a6",
    "workbench.scrollbar.thumb.active.foreground": "#c8c8c8",

    "workbench.panel.background": "#ffffff",
    "workbench.panel.options.hover.background": "#f3f3f3",
    "workbench.panel.options.active.background": "#bfbfbf",
    "workbench.panel.options.active.border.foreground": "#d4d4d4",

    "workbench.dialog.background": "#ffffff",
    "workbench.dialog.foreground": "#1e1e1e",
    "workbench.dialog.hover.background": "#f3f3f3",
    "workbench.dialog.hover.foreground": "#1e1e1e",

    "workbench.editor.background": "#ffffff",
    "workbench.editor.foreground": "#1e1e1e",
    "workbench.editor.cursor.foreground": "#1e1e1e",
    "workbench.editor.line.highlight.background": "#f0f8ff",
    "workbench.editor.suggestion.active.background": "#cce7ff",
    "workbench.editor.widget.background": "#f3f3f3",

    "workbench.preview.markdown.code.background": "#f6f8fa",

    "workbench.mira.message.user.background": "#f3f3f3",
    "workbench.mira.message.user.foreground": "#1e1e1e",
    "workbench.mira.message.user.border.foreground": "#007acc",
    "workbench.mira.message.ai.background": "#ffffff",
    "workbench.mira.message.ai.foreground": "#424242",
    "workbench.mira.message.ai.border.foreground": "#d4d4d4",
    "workbench.mira.chatbox.background": "#f3f3f3",
    "workbench.mira.chatbox.foreground": "#424242",
    "workbench.mira.chatbox.border.foreground": "#d4d4d4",
    "workbench.mira.chatbox.active.border.foreground": "#007acc",
    "workbench.mira.voice.caption.active.background": "#ff7800",

    "workbench.activitybar.background": "#f0f0f0",
    "workbench.activitybar.hover.background": "#dedede",
    "workbench.activitybar.active.background": "#d4d4d4",

    "workbench.titlebar.background": "#f0f0f0",
    "workbench.titlebar.foreground": "#1e1e1e",
    "workbench.titlebar.item.hover.background": "#e8e8e8",
    "workbench.titlebar.window.controls.circle.foreground": "#d4d4d4",
    "workbench.titlebar.search.background": "#ffffff",
    "workbench.titlebar.search.foreground": "#1e1e1e",
    "workbench.titlebar.search.hover.outline": "#007acc",
    "workbench.titlebar.menu.background": "#ffffff",
    "workbench.titlebar.menu.foreground": "#1e1e1e",
    "workbench.titlebar.menu.item.hover.background": "#e1f4ff",

    "workbench.terminal.background": "#ffffff",
    "workbench.terminal.foreground": "#1e1e1e",
    "workbench.terminal.cursor.foreground": "#1e1e1e",
    "workbench.terminal.selection.background": "#f0f8ff",

    "workbench.terminal.black": "#333333",
    "workbench.terminal.red": "#d73a49",
    "workbench.terminal.green": "#22863a",
    "workbench.terminal.darkgreen": "#90EE90",
    "workbench.terminal.yellow": "#b08800",
    "workbench.terminal.blue": "#0366d6",
    "workbench.terminal.magenta": "#6f42c1",
    "workbench.terminal.cyan": "#1b7c83",
    "workbench.terminal.white": "#586069",
    "workbench.terminal.bright.black": "#6a737d",
    "workbench.terminal.bright.red": "#cb2431",
    "workbench.terminal.bright.green": "#28a745",
    "workbench.terminal.bright.yellow": "#bf9405",
    "workbench.terminal.bright.blue": "#2188ff",
    "workbench.terminal.bright.magenta": "#8a63d2",
    "workbench.terminal.bright.cyan": "#0397d3",
    "workbench.terminal.bright.white": "#1e1e1e",

    "workbench.mira.voice.color.violet": "102, 51, 153",
    "workbench.mira.voice.color.orange": "255, 120, 0",
    "workbench.mira.voice.color.black": "0, 0, 0",
    "workbench.mira.voice.color.white": "255, 255, 255",

    "workbench.statusbar.background": "#f0f0f0",
    "workbench.statusbar.foreground": "#6c6c6c",
    "workbench.statusbar.item.hover.background": "#e8e8e8",

    "workbench.drawboard.background": "#ffffff",
    "workbench.drawboard.canvas.background": "#f0f0f0",
    "workbench.drawboard.canvas.grid.background": "#e6e6e6",
    "workbench.drawboard.canvas.stroke.foreground": "#007acc",
    "workbench.drawboard.tools.background": "#f3f3f3",
    "workbench.drawboard.tools.tool.active.background": "#007acc",
    "workbench.drawboard.tools.tool.hover.background": "#e1f4ff",
    "workbench.drawboard.tools.tool.active.border.foreground": "#005a9e",

    "workbench.jupyter.notebook.background": "#f3f3f3",
    "workbench.jupyter.notebook.tools.background": "#f3f3f3",
    "workbench.jupyter.notebook.tools.hover.background": "#e0e0e0",
    "workbench.jupyter.notebook.active.cell.border.foreground": "#2188ff",

    "workbench.files.default.foreground": "#1e1e1e",
    "workbench.files.modified.foreground": "#b08800",
    "workbench.files.untracked.foreground": "#22863a",
    "workbench.files.ignored.foreground": "#6a737d",
    "workbench.files.error.foreground": "#d73a49",
  },
  tokenColors: {
    default: "#333333",
    keyword: "#af00db",
    "keyword.json": "#d73a49",
    "keyword.typeModifier": "#0969da",
    metadata: "#e36209",
    number: "#0969da",
    boolean: "#0969da",
    string: "#032f62",
    "string.binary": "#e36209",
    "string.escape": "#0550ae",
    "string.escape.alternative": "#6f42c1",
    "string.format.item": "#e36209",
    "string.regexp": "#116329",
    identifier: "#d73a49",
    "identifier.this": "#e36209",
    "identifier.constant": "#e36209",
    "identifier.variable.local": "#953800",
    "identifier.parameter": "#953800",
    "identifier.function.declaration": "#8250df",
    "identifier.method.static": "#8250df",
    "identifier.builtin": "#0550ae",
    "identifier.type": "#116329",
    "identifier.field": "#8250df",
    "identifier.field.static": "#8250df",
    "identifier.interface": "#116329",
    "identifier.type.class": "#116329",
    comment: "#6a737d",
    "comment.parameter": "#6a737d",
    punctuation: "#24292f",
  },
};

export const Dark: ITheme = {
  name: "Dark",
  kind: "dark",
  colors: {
    "workbench.background": "#141414",
    "workbench.foreground": "#e6e6e6",
    "workbench.hover.background": "#2A2A2A99",
    "workbench.secondary.foreground": "#e6e6e699",
    "workbench.border.foreground": "#e6e6e60D",
    "workbench.icon.foreground": "#e6e6e699",
    "workbench.item.hover.background": "#2A2A2A99",

    "workbench.primary.button.background": "#81A1C1",
    "workbench.primary.button.foreground": "#191c22",
    "workbench.secondary.button.background": "#2A2A2A99",
    "workbench.secondary.button.foreground": "#ececec",

    "workbench.button.border": "#2A2A2A",
    "workbench.button.separator": "#2A2A2A",
    "workbench.secondary.button.border": "#2A2A2A",

    "workbench.input.background": "#2A2A2A55",
    "workbench.input.foreground": "#e6e6e6",
    "workbench.input.active.outline": "#e6e6e6",
    "workbench.input.outline": "#2A2A2A",
    "workbench.input.icon.foreground": "#e6e6e699",

    "workbench.tabs.background": "#141414",
    "workbench.tabs.foreground": "#505050",
    "workbench.tabs.icon.foreground": "#505050",
    "workbench.tabs.icon.active.foreground": "#e6e6e6",
    "workbench.tabs.hover.background": "#e6e6e600",
    "workbench.tabs.active.background": "#222222",
    "workbench.tabs.active.foreground": "#e6e6e6",
    "workbench.tabs.active.border.foreground": "#1a1a1a",

    "workbench.scrollbar.background": "#00000000",
    "workbench.scrollbar.thumb.foreground": "#40404055",
    "workbench.scrollbar.thumb.hover.foreground": "#40404055",
    "workbench.scrollbar.thumb.active.foreground": "#60606055",

    "workbench.panel.background": "#141414",
    "workbench.panel.options.hover.background": "#2A2A2AB3",
    "workbench.panel.options.active.background": "#404040",
    "workbench.panel.options.active.border.foreground": "#e6e6e600",

    "workbench.dialog.background": "#141414",
    "workbench.dialog.foreground": "#e6e6e6",
    "workbench.dialog.hover.background": "#2A2A2A99",
    "workbench.dialog.hover.foreground": "#e6e6e6",

    "workbench.editor.background": "#181818",
    "workbench.editor.foreground": "#D8DEE9",
    "workbench.editor.cursor.foreground": "#e6e6e6",
    "workbench.editor.suggestion.active.background": "#404040",
    "workbench.editor.widget.background": "#141414",
    "workbench.editor.line.highlight.background": "#292929",

    "workbench.preview.markdown.code.background": "#2A2A2A99",

    "workbench.preview.markdown.copy.background": "#141414",
    "workbench.preview.markdown.copy.hover.background": "#050505",

    "workbench.preview.markdown.run.background": "#141414",
    "workbench.preview.markdown.run.hover.background": "#0C0C0C",

    "workbench.preview.markdown.hr.foreground": "#2A2A2A",

    "workbench.mira.message.user.background": "#2A2A2A99",
    "workbench.mira.message.user.foreground": "#e6e6e6",
    "workbench.mira.message.user.border.foreground": "#81A1C1",
    "workbench.mira.message.ai.background": "#141414",
    "workbench.mira.message.ai.foreground": "#e6e6e699",
    "workbench.mira.message.ai.border.foreground": "#2A2A2A",

    "workbench.mira.chatbox.background": "#2A2A2A55",
    "workbench.mira.chatbox.foreground": "#e6e6e699",
    "workbench.mira.chatbox.border.foreground": "#2A2A2A",
    "workbench.mira.chatbox.active.border.foreground": "#e6e6e6",

    "workbench.mira.voice.caption.active.background": "#ff7800",

    "workbench.activitybar.background": "#141414",
    "workbench.activitybar.hover.background": "#2A2A2A99",
    "workbench.activitybar.icon.foreground": "#424242",
    "workbench.activitybar.icon.active.foreground": "#e6e6e6",
    "workbench.activitybar.active.background": "#2A2A2A99",

    "workbench.titlebar.background": "#141414",
    "workbench.titlebar.foreground": "#e6e6e682",
    "workbench.titlebar.item.hover.background": "#2A2A2A99",
    "workbench.titlebar.window.controls.circle.foreground": "#505050",

    "workbench.titlebar.search.background": "#2A2A2A55",
    "workbench.titlebar.search.foreground": "#e6e6e6",
    "workbench.titlebar.search.hover.outline": "#e6e6e6",

    "workbench.titlebar.menu.background": "#141414",
    "workbench.titlebar.menu.foreground": "#e6e6e6",
    "workbench.titlebar.menu.item.hover.background": "#2A2A2A99",

    "workbench.terminal.background": "#141414",
    "workbench.terminal.foreground": "#e6e6e6cc",
    "workbench.terminal.cursor.foreground": "#e6e6e6",
    "workbench.terminal.selection.background": "#636262dd",

    "workbench.terminal.black": "#2A2A2A",
    "workbench.terminal.red": "#BF616A",
    "workbench.terminal.green": "#A3BE8C",
    "workbench.terminal.darkgreen": "#254738",
    "workbench.terminal.yellow": "#EBCB8B",
    "workbench.terminal.blue": "#81A1C1",
    "workbench.terminal.magenta": "#B48EAD",
    "workbench.terminal.cyan": "#88C0D0",
    "workbench.terminal.white": "#e6e6e6",

    "workbench.terminal.bright.black": "#505050",
    "workbench.terminal.bright.red": "#BF616A",
    "workbench.terminal.bright.green": "#A3BE8C",
    "workbench.terminal.bright.yellow": "#EBCB8B",
    "workbench.terminal.bright.blue": "#81A1C1",
    "workbench.terminal.bright.magenta": "#B48EAD",
    "workbench.terminal.bright.cyan": "#88C0D0",
    "workbench.terminal.bright.white": "#e6e6e6",

    "workbench.mira.voice.color.violet": "0, 20, 255",
    "workbench.mira.voice.color.orange": "255, 120, 0",
    "workbench.mira.voice.color.black": "10, 10, 10",
    "workbench.mira.voice.color.white": "230, 230, 230",

    "workbench.statusbar.background": "#141414",
    "workbench.statusbar.foreground": "#e6e6e682",
    "workbench.statusbar.item.hover.background": "#404040",

    "workbench.drawboard.background": "#141414",
    "workbench.drawboard.canvas.background": "#1a1a1a",
    "workbench.drawboard.canvas.grid.background": "#2A2A2A",
    "workbench.drawboard.canvas.stroke.foreground": "#88C0D0",

    "workbench.drawboard.tools.background": "#141414",
    "workbench.drawboard.tools.tool.active.background": "#81A1C1",
    "workbench.drawboard.tools.tool.hover.background": "#2A2A2A99",
    "workbench.drawboard.tools.tool.active.border.foreground": "#81A1C1",

    "workbench.jupyter.notebook.background": "#141414",
    "workbench.jupyter.notebook.tools.background": "#141414",
    "workbench.jupyter.notebook.tools.hover.background": "#2A2A2A99",

    "workbench.files.default.foreground": "#808080",
    "workbench.files.icon.foreground": "#808080",
    "workbench.files.modified.foreground": "#EBCB8B",
    "workbench.files.untracked.foreground": "#A3BE8C",
    "workbench.files.ignored.foreground": "#505050",
    "workbench.files.error.foreground": "#BF616A",
  },

  tokenColors: {
    default: "#d6d6dd",
    keyword: "#83d6c5",
    "keyword.json": "#E06C75",
    "keyword.typeModifier": "#82d2ce",
    source: "#d9a654",
    metadata: "#f8c762",
    number: "#ebc88d",
    boolean: "#82d2ce",
    string: "#e394dc",
    "string.binary": "#a8cc7c",
    "string.escape": "#d6d6dd",
    "string.escape.alternative": "#af9cff",
    "string.format.item": "#f8c762",
    "string.regexp": "#d6d6dd",
    identifier: "#d6d6dd",
    "identifier.this": "#efb080",
    "identifier.constant": "#83d6c5",
    "identifier.variable.local": "#d1d1d1",
    "identifier.parameter": "#f8c762",
    "identifier.function.declaration": "#efb080",
    "identifier.method.static": "#efb080",
    "identifier.builtin": "#82d2ce",
    "identifier.type": "#efb080",
    "identifier.field": "#AA9BF5",
    "identifier.field.static": "#AA9BF5",
    "identifier.interface": "#87c3ff",
    "identifier.type.class": "#87c3ff",
    comment: "#707070",
    "comment.parameter": "#e6e6e65C",
    punctuation: "#d6d6dd",
  },
};
